//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EmployeeRoster
    {
        public long EmployeeRoasterId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> RoasterId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> WeekNo { get; set; }
        public Nullable<System.DateTime> RosterDate { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CompanyBranchId { get; set; }
    }
}
