//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_ResourceRequisitionSkill
    {
        public int RequisitionSkillId { get; set; }
        public Nullable<int> RequisitionId { get; set; }
        public Nullable<int> SkillId { get; set; }
    }
}
