//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankStatementDetail
    {
        public int BankStatementDetailId { get; set; }
        public Nullable<long> BankStatementId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<decimal> Withdrawal { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Narration { get; set; }
    }
}
