//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarryForwardChasi
    {
        public long CarryForwardID { get; set; }
        public string CarryForwardNo { get; set; }
        public Nullable<System.DateTime> CarryForwardDate { get; set; }
        public Nullable<long> CompanyBranchId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> PrevChasisMonth { get; set; }
        public Nullable<int> PrevChasisYear { get; set; }
        public Nullable<int> CarryForwardMonth { get; set; }
        public Nullable<int> CarryForwardYear { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<int> CarryForwardSequence { get; set; }
    }
}
