//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChasisSerialPlanDetail
    {
        public long ChasisSerialDetailID { get; set; }
        public Nullable<long> ChasisSerialPlanID { get; set; }
        public Nullable<int> ChasisModelID { get; set; }
        public string ChasisSerialNo { get; set; }
        public string MotorNo { get; set; }
        public Nullable<long> IncrementalNo { get; set; }
        public Nullable<bool> Consumed { get; set; }
        public Nullable<int> CarryForwardMonth { get; set; }
        public Nullable<int> CarryForwardYear { get; set; }
    }
}
