//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChasisSerialMapping
    {
        public long MappingId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public string ChasisSerialNo { get; set; }
        public string MotorNo { get; set; }
        public string ControllerNo { get; set; }
        public string Color { get; set; }
        public string BatteryPower { get; set; }
        public string BatterySerialNo1 { get; set; }
        public string BatterySerialNo2 { get; set; }
        public string BatterySerialNo3 { get; set; }
        public string BatterySerialNo4 { get; set; }
        public string Tier { get; set; }
        public Nullable<bool> FrontGlassAvailable { get; set; }
        public Nullable<bool> ViperAvailable { get; set; }
        public Nullable<bool> RearShockerAvailable { get; set; }
        public Nullable<bool> ChargerAvailable { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> FM { get; set; }
        public Nullable<int> CompanyBranchId { get; set; }
        public string ProductSerialStatus { get; set; }
    }
}
