//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchProductDetail
    {
        public long DispatchDetailID { get; set; }
        public Nullable<int> DispatchID { get; set; }
        public Nullable<int> SOId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Priority { get; set; }
    
        public virtual Dispatch Dispatch { get; set; }
    }
}
