//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCard
    {
        public long JobCardID { get; set; }
        public string JobCardNo { get; set; }
        public Nullable<System.DateTime> JobCardDate { get; set; }
        public string TimeIn { get; set; }
        public string DeliveryTime { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string ModelName { get; set; }
        public string RegNo { get; set; }
        public string FrameNo { get; set; }
        public string EngineNo { get; set; }
        public Nullable<System.DateTime> DateOfSale { get; set; }
        public string KMSCovered { get; set; }
        public string CouponNo { get; set; }
        public string FuelLevel { get; set; }
        public string EngineOilLevel { get; set; }
        public string KeyNo { get; set; }
        public string BatteryMakeNo { get; set; }
        public string Damage { get; set; }
        public string Accessories { get; set; }
        public string TypeOfService { get; set; }
        public string EstimationDeliveryTime { get; set; }
        public Nullable<decimal> EstimationCostOfRepair { get; set; }
        public Nullable<decimal> EstimationCostOfParts { get; set; }
        public string PreJobCardNo { get; set; }
        public Nullable<System.DateTime> PreSeviceDate { get; set; }
        public string PreKey { get; set; }
        public string MahenicName { get; set; }
        public string StartTime { get; set; }
        public string ClosingTime { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> JobCardSequence { get; set; }
        public string VehicleNo { get; set; }
        public string ChassisNo { get; set; }
    }
}
