//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSubCategoryStateTaxMapping
    {
        public long MappingId { get; set; }
        public Nullable<int> ProductSubGroupId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> TaxId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
