//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoiceImportProductDetail
    {
        public long InvoiceProductDetailId { get; set; }
        public Nullable<long> InvoiceId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public string ProductShortDesc { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> IGST_Perc { get; set; }
        public Nullable<decimal> IGST_Amount { get; set; }
        public string HSN_Code { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string RITC { get; set; }
        public Nullable<decimal> AssValue { get; set; }
        public Nullable<decimal> CTH { get; set; }
        public string CETH { get; set; }
        public string CNotn { get; set; }
        public string ENotn { get; set; }
        public string RSP { get; set; }
        public Nullable<decimal> LoadProv { get; set; }
        public Nullable<decimal> BCDAmtRs { get; set; }
        public Nullable<decimal> CVDAmtRs { get; set; }
        public Nullable<decimal> CustomDutyPerc { get; set; }
        public Nullable<decimal> CustomDutyRate { get; set; }
        public Nullable<decimal> ExciseDutyPerc { get; set; }
        public Nullable<decimal> ExciseDutyRate { get; set; }
        public Nullable<decimal> GSTCessPerc { get; set; }
        public Nullable<decimal> GSTCessAmt { get; set; }
        public string ENSNO { get; set; }
        public string CNSNO { get; set; }
        public Nullable<decimal> EducationalCessOnCVDPerc { get; set; }
        public Nullable<decimal> EducationalCessOnCVDAmt { get; set; }
        public Nullable<decimal> SecHigherEduCessOnCVDPerc { get; set; }
        public Nullable<decimal> SecHigherEduCessOnCVDAmt { get; set; }
        public Nullable<decimal> CustomSecHigherEduCessPerc { get; set; }
        public Nullable<decimal> CustomSecHigherEduCessAmt { get; set; }
        public Nullable<decimal> CustomEducationalCessPerc { get; set; }
        public Nullable<decimal> CustomEducationalCessAmt { get; set; }
    }
}
